title: "RubyMine入門"
summary: "RubyMineを使い始めたけど、使いこなせない...という人向けの入門書"
topics: ["RubyMine", "Ruby", "Rails"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - about
  - preparation
  - search-everywhere
  - basic-file-operation
  - basic-text-operation
  - run-source
  - debug
  - refactoring
  - git
  - local-history
  - terminal
  - run-anything
  - db-client
  - appearance
toc_depth: 2
